#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"
#include <iostream>
#include <string>
#include <vector>
#include "Wire.h"
#include "Gate.h"
#include "Event.h"
#include <fstream>
#include <sstream>
#include <queue>

using namespace std;

//// end generated include

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
	protected:
		// Handlers for GUIClass events.
		void CircuitFileAdded( wxFileDirPickerEvent& event );
		void VectorFileAdded( wxFileDirPickerEvent& event );
		void StartSimulation( wxCommandEvent& event );

		wxString circuitFilePath;
		wxString vectorFilePath;
		wxTextCtrl* findSimulationSpace(); 

		void readFunctionFile(vector<Wire*>& w, vector<Gate*>& g);
		void readVectorFile(vector<Wire*>& w, vector<Gate*>& g, priority_queue<Event>& eq);
		void simulate(vector<Wire*>& w, vector<Gate*>& g, priority_queue<Event>& eq);
		void printSimulation(vector<Wire*>& w);
	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
		
	//// end generated class members
	
};

#endif // __SubGUIClass__
